### ISSUE TITLE
Wordsmithing error in draft-ietf-tsvwg-udp-options-23 Section 9.4

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-ietf-tsvwg-udp-options#20]
After Step 1 of the description of how packets are fragmented:

OLD:
>>      >> The UDP checksum of the original packet SHOULD be set to zero
>>      if protection is provided by use of a non-zero OCS in each
>>      fragment.
NEW:
>>      >> The UDP checksum of the original packet SHOULD be set to zero
>>      since there is no provision to transmit it. Equivalent protection
>>      will be provided if each fragment has a non-zero OCS value, as
>>      will be the case if each fragment’s UDP checksum is non-zero.
>>      Similarly, the OCS value of the original packet SHOULD be zero
>>      if each fragment will have a non-zero OCS value, as will be the
>>      case if each fragment’s UDP checksum is non-zero.

Four sentences were removed in transcribing the proposed text posted on the list into the new draft. This resulted in a change of meaning that is not correct. The above change would restore the proposed text, but any wordsmithing that keeps the same meaning would be fine.

**Comment by jtouch** [comment]
Done in -24 (to be posted)

**Comment by Mike-Heard** [comment]
This is still not resolved. The text after Step 1 of the description of how packets are fragmented (now mislabeled as Step 7)  now reads:
> > ```
> > >> The UDP checksum of the original packet SHOULD be set to zero
> > if protection is provided by use of a non-zero OCS in each
> > fragment. Equivalent protection will be provided if each fragment
> > has a non-zero OCS value, as will be the case if each fragment's
> > UDP checksum is non-zero. Similarly, the OCS value of the
> > original packet SHOULD be zero if each fragment will have a non-
> > zero OCS value, as will be the case if each fragment's UDP
> > checksum is non-zero.
> > ```

It should read:
> > > ```
> > >  >> The UDP checksum of the original packet SHOULD be set to zero
> > >  since there is no provision to transmit it. Equivalent protection
> > >  will be provided if each fragment has a non-zero OCS value, as
> > >  will be the case if each fragment’s UDP checksum is non-zero.
> > >  Similarly, the OCS value of the original packet SHOULD be zero
> > >  if each fragment will have a non-zero OCS value, as will be the
> > >  case if each fragment’s UDP checksum is non-zero.
> > > ```

In other words, s/if protection is provided by use of a non-zero OCS in each fragment/since there is no provision to transmit it/. A means to transmit the original UDP CS was dropped from the fragment format many revisions ago since OCS on the fragments provides equivalent protection.

**Comment by jtouch** [comment]
Fixed in -25. FWIW, it helps to flag the actual text being changed ;-)

**Comment by Mike-Heard** [comment]
Text looks good in -28, so I am closing the issue. The errant step numbers are noted in a comment to #22.
